services:
  met-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: met-app
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DISCORD_CALLBACK_URL=https://met.3r6nuss.de/auth/discord/callback
    restart: unless-stopped

networks:
  default:
    name: nginx-proxy-manager_default
    external: true
